### ISSUE TITLE
Publish 0.2.1

### ISSUE THREAD

**Issue by jonasfj** [jcmellado/dartis#14]
Given that we've now enabled consumers to handled broken connections, can we publish a version 0.2.1?

**Comment by jcmellado** [comment]
I'm still facing https://github.com/jcmellado/dartis/issues/8#issuecomment-444582903

Windows 10 64 bits
Dart 2.1.0

Note: New version will be 0.3.0

**Comment by jonasfj** [comment]
hmm, I haven't really tried windows in a while.. interesting..

**Comment by jcmellado** [comment]
The new feature needs a bit more of testing, I added two new tests right now
