### ISSUE TITLE
Using `multi/exec` asynchronously, aka transaction queueing

### ISSUE THREAD

**Issue by emeyex** [jcmellado/dartis#17]
I was running into a seemingly random race condition error of the form:
```
RedisException: ERR MULTI calls can not be nested
```
and traced it down to asynchronous code execution. I.e., imagine you are sharing one Redis connection across several handlers, I was running into the following situation:

HANDLER 1:
await client.multi()
... starts waiting ...

HANDLER 2:
await client.multi()
throws ERROR bcz execution has not yet returned to HANDLER 1

I ended up implementing my own "transaction queueing" system (one per client connection), to ensure that I never had more than one MULTI/EXEC sequence in flight at a time. I found that with all the inherent asynchrony of dart, it could be very hard if not impossible to guarantee that you never nested calls.

I wanted to a) make sure I'm not just doing something stupid, i.e., is there a better or simpler solution, and b) assuming this is a realistic scenario, wanted to put forward the idea of embedding this sort of transaction queueing in the library itself. I thought it a somewhat subtle bug that only cropped up when I started running unit tests with multiple handlers firing off, and even then, it was far from 100%. With queueing embedded in the library itself, it might prevent people from shooting themselves in the foot.

**Comment by jcmellado** [comment]
The library doesn't share anything. Each client has its own connection.

I'm not sure if you are trying to use the same client in some asynchronous code and calling MULTI before EXEC or ABORT. Create a new connection for each flow, they are cheap, or ensure your program is really waiting for the end of the previous MULTI command. You could activate the log to get more information.

And please, note that Redis transactions are deprecated (by Redis itself) in favor of Lua scripting.

**Comment by emeyex** [comment]
Where do you see that they're deprecated? https://redis.io/topics/transactions alludes to the _possibility_ that _some day_ they may be, but in the preceding paragraph it also makes the point that transactions still have value and probably won't go away... don't get me wrong, scripts are great, but it's still easier and faster to use transactions where appropriate.

As far as using a new connection for each request handler, that seems a bit wasteful and potentially delays the response time. I prefer sharing connections where possible, and with an application-level transaction queue, I'm no longer running into the problem. It's just something I wanted to bring up as I could envision other users stumbling into it unwittingly.

In any case, thanks for the library, it's great to see a first-class Redis client in Dart!

**Comment by jcmellado** [comment]
Ok, maybe "deprecated" is not the correct word, English is not my mother tongue.

I don't know how you are using Redis, that's the reason why I wrote "flow", not "handler".

Anyway, thanks for reporting it.

**Comment by emeyex** [comment]
No worries! Just to give you an idea of what I'm talking about, my queueing stuff is pretty simple. It boils down to the following two methods (on a "client wrapper" class):

```
  Future runTransaction(Function fn) async {
    final done = Completer();
    _transactions.add(() async {
      await commands.multi();
      await fn();
      await commands.exec();
      done.complete();
    });
    _processTransactions();
    await done.future;
  }
  void _processTransactions() {
    if(_transactionsInProgress) {
      return;
    }
    _transactionsInProgress = true;
    Future.microtask(() async {
      assert(!_transactions.isEmpty && _transactionsInProgress);
      await _transactions.first();
      _transactions.removeAt(0);
      _transactionsInProgress = false;
      if(!_transactions.isEmpty) {
        _processTransactions();
      }
    });
  }
```

**Comment by jcmellado** [comment]
Could this be closed then?

And of course, if you are sharing the same connection between different asynchronous blocks of code then you really need a synchronization method that works for you.

**Comment by emeyex** [comment]
Sure. If you're not interested in adding/modifying the API, then it might at least be worth adding a note in the docs to `.multi()` and `.exec()`? Up to you of course.
