### ISSUE TITLE
Full support for PubSub

### ISSUE THREAD

**Issue by hitecherik** [jcmellado/dartis#18]
I've noticed that your README says in the Publish/Subscribe section:

> In this mode the only allowed commands are `subscribe`, `unsubscribe`, `psubscribe`, `punsubscribe`, `ping` and `quit`.

Is there any planned support for the [`publish` operation](https://redis.io/commands/publish)?

**Comment by jcmellado** [comment]
All Redis Pub/Sub commands are already implemented. That is, `publish` is already available.

Take a look to these tests:
https://github.com/jcmellado/dartis/blob/master/test/client/pubsub_test.dart

When a Redis client is subscribed to one or more channels, the only allowed commands are `subscribe`, `unsubscribe`, `psubscribe`, `punsubscribe`, `ping` and `quit`. But this is NOT a restriction of the library, is a restriction of the Redis server itself.

Take a look to the official Redis documentation:
https://redis.io/topics/pubsub

You must open a client in Pub/Sub mode, and another client in "normal" mode to publish messages.

**Comment by hitecherik** [comment]
That makes complete sense, thank you!
