### ISSUE TITLE
"pubsub.stream.listen(print, onDone: (){print('done')}). " the "onDone:" never work.

### ISSUE THREAD

**Issue by winner484** [jcmellado/dartis#20]
void main() async {
      final pubsub = await redis.PubSub.connect<String, String>('redis://localhost:6379');

    // Subscribe to some channels and patterns
      pubsub
        ..subscribe(channel: 'dev.dart')
        ..psubscribe(pattern: 'message');

    // Listen for server replies
      pubsub.stream.listen(print, onDone: (){
        print('done');
      });

the onDone:(){print('done')} never worked when get a message from redis.
All i want is running a custom function with the message received from redis when a new message come in.
SOS!

**Comment by jcmellado** [comment]
> All i want is running a custom function with the message received from redis when a new message come in.

You must use the `onData` handler instead of the `onDone` one.

Take a look to the signature of the `listen` method:
```
listen(void onData(T event), { Function onError, void onDone(), bool cancelOnError ...
```

The first parameter is what you are looking for:
```
pubsub.stream.listen(onData);
...
void onData(redis.PubSubEvent event) {
  if (event is redis.MessageEvent) (
    ...
    <<put your custom code here>>
    ...
  }
});
```
