### ISSUE TITLE
Connection with password

### ISSUE THREAD

**Issue by nalek7** [jcmellado/dartis#23]
I have redis in the cloud service. The connection string looks like redis://login:password@host:port.
When executing any command, it gives an error: RedisException: NOAUTH Authentication required.
How make auth?

**Comment by jcmellado** [comment]
Just call the Redis AUTH command:

`await commands.auth(password)`

There are not users in Redis:
https://redis.io/commands/auth

**Comment by nalek7** [comment]
> Just call the Redis AUTH command:
> 
> `await commands.auth(password)`
> 
> There are not users in Redis:
> https://redis.io/commands/auth

Ок, thx!
