### ISSUE TITLE
Supply password with PubSub

### ISSUE THREAD

**Issue by CollinAlpert** [jcmellado/dartis#24]
Is it somehow possible to supply the password to the redis server when connecting with PubSub?

**Comment by jcmellado** [comment]
I have released a new dartis version 0.4.0.

Now you can create a Redis connection, call the AUTH Redis command, and create the PubSub object with that authorized connection:

```dart
final client = await Client.connect('redis://localhost:6379');

final commands = client.asCommands<String, String>();

await commands.auth('password');

// Create the PubSub object using the client connection
final broker = PubSub<String, String>(client.connection);
```

Let me know if this solution solves your issue.

**Comment by CollinAlpert** [comment]
Now I am getting the exception "Unhandled Exception: RedisException: Unexpected value of type "BulkReply"." when listening to a subscription. The BulkReply which gets passed to the `convert` method in codec.dart is "BulkReply: [115, 117, 98, 115, 99, 114, 105, 98, 101]"

**Comment by jcmellado** [comment]
Are you using the client instance for running any other commands beyond the first AUTH?

**Comment by CollinAlpert** [comment]
Nothing except the commands from your example. After the AUTH I do a SUBSCRIBE and then listen.

**Comment by jcmellado** [comment]
This is all the code that I'm using for testing:

```dart
import 'dart:io' show exit, ProcessSignal;

import 'package:dartis/dartis.dart' as redis show Client, PubSub;

void main() async {
  final client = await redis.Client.connect('redis://localhost:6379');

  final commands = client.asCommands<String, String>();

  await commands.auth('password');

  final broker = redis.PubSub<String, String>(client.connection);

  // Ctrl+C handler.
  ProcessSignal.sigint.watch().listen((_) async {
    await broker.disconnect();
    exit(0);
  });

  broker.stream.listen(print, onError: print, onDone: () => exit(0));

  broker.subscribe(channel: 'news.dartis');

  // This works too => broker.psubscribe(pattern: 'news.*');
}
```

Could you run this code? Sorry, maybe I'm missing something.

**Comment by CollinAlpert** [comment]
Ah, I had used `PubSub(client.connection)` instead of `PubSub<String, String>(client.connection)`. Now everything works like a charm. Thanks!
