### ISSUE TITLE
publish problem

### ISSUE THREAD

**Issue by inayir** [jcmellado/dartis#30]
This code is running but publish command is not run. Error is: "ERR only (P)SUBSCRIBE / (P)UNSUBSCRIBE / PING / QUIT allowed in this context" Connection is OK, from Node.js message is received. What can I do? 

final broker = PubSub<String, String>(client.connection);
  // Outputs the data received from the server.
  broker.stream.listen(print, onError: print, onDone: () => exit(0));

  // Subscribes the client to some channels.
  var hchannel='haber';
  var kanal=broker.subscribe(channel: hchannel);

  var bmessage='Ilk Mesajımız geldi mi?';
  commands.publish(hchannel, bmessage);

**Comment by jcmellado** [comment]
Verify that you are **not** using the same connection for subscribing and publishing.

One client connection for subscribing:
```
final broker = await redis.PubSub.connect<String, String>('redis://localhost:6379');
broker.subscribe(...);
```

Another different client connection for publishing:
```
final client = await Client.connect('redis://localhost:6379');
final commands = client.asCommands<String, String>();
commands.publish(..., ...);
```

**Comment by inayir** [comment]
Ok. 
Thanks you. 

İbrahim Nayir 
qrvisit.com/inayir
