### ISSUE TITLE
Can pipeline have unwanted results?

### ISSUE THREAD

**Issue by jodinathan** [jcmellado/dartis#42]
I was digging through the pipline feature in the lib and I am wondering if it can lead to weird behavior?  

It sets ```_pipeline``` to true and then the subsequent command calls are stored and only executed when calling ```flush```, however, can't it also store command calls from other parts of the code?  

If we have two places in the code using the same client and one is using pipeline and other isn't, if they run at same time, wouldn't the commands that aren't supposed to be in pipeline also be executed in the pipeline because of the pipeline call?  

Is this expected?  
Should I create another client just for pipelining purposes?  
I am not an expert in Redis and this is my first time using pipeline, so I wouldn't know.

**Comment by jcmellado** [comment]
That's the expected behavior, you should not use the same connection with different purposes without expecting unwanted results.

**Comment by jodinathan** [comment]
okay
