### ISSUE TITLE
Can I use RedisSearch?

### ISSUE THREAD

**Issue by jodinathan** [jcmellado/dartis#43]
I am kinda new to Redis and surely new to RediSearch and, from what I am studying, using RediSearch is dependent on the client you are using.  
As I couldn't find an example with RediSearch in the documentation, I wonder if is it possible to use RediSearch with this package?

**Comment by jodinathan** [comment]
It seems I can build the interface to use the modules using ```ModuleBase```.  

Do you know if anyone has created an interface for RediSearch?  

it would be nice to have and we could also add this package to the RediSearch clients list

**Comment by jcmellado** [comment]
Yes, a module is the way to go.
