### ISSUE TITLE
RedisException: NOAUTH Authentication required.

### ISSUE THREAD

**Issue by coylums** [jcmellado/dartis#6]
This package is working great, when deploying to Heroku and using their secure connection string, this package, per documentation, doesn't support a username/password at this time in the connection string. I'm going to try and see if I can add it and create a PR.

**Comment by jcmellado** [comment]
AFAIK, Redis doesn't have the concept of "username", but a password can be provided calling the [AUTH](https://github.com/jcmellado/dartis/blob/master/lib/src/commands/connection.dart#L10) command:

```dart
await commands.auth('password');
```

**Comment by coylums** [comment]
Yes, after reading a little more, there's not user, the Heroku connectionString has one but it is ignored.
