### ISSUE TITLE
Handling broken connections?

### ISSUE THREAD

**Issue by jonasfj** [jcmellado/dartis#8]
As far as I can see connection errors are not handled and thrown to the global exception handler, which terminates the process. But in many cases it might be nice to support reconnecting.

If using redis as a single key/value cache... it would be preferred to reconnect and retry get/sets instead of crashing the entire process.

I think it's possible to handle errors by setting up a zone and handling the error, but:
 1) This seems like an unfortunate way to this,
 2) All pending commands are going to hang because the futures aren't resolved.

I think we could solve (2) by resolving all `_unreplied` commands in:
https://github.com/jcmellado/dartis/blob/00a30ebb97806e7f70ebe046ddb734dc17045f19/lib/src/client/client.dart#L282-L285

Otherwise, we essentially have futures that will never be resolved. We can just complete all the futures with some generic error, but without an error downstreamer are going to hang..

Am I missing something? I'm not sure exactly how to expose the error from (1), but if the commands return with a specific error when the connection is broken then it becomes a lot easier to wrap with retry logic.

**Comment by jcmellado** [comment]
> As far as I can see connection errors are not handled and thrown to the global exception handler, which terminates the process. But in many cases it might be nice to support reconnecting.

Yes, but it seemed a bit hard to implement correctly to me, so I left out it from the very first version of the library. The main purpose of the library is implement the Redis protocol, of course.

> If using redis as a single key/value cache... it would be preferred to reconnect and retry get/sets instead of crashing the entire process.

Indeed.

But note that the reconnection could not satisfy the client expectation when using the "pipelining" feature. And the reconnection should be disabled when using the "fire and forget" feature.

> I think it's possible to handle errors by setting up a zone and handling the error, but:
This seems like an unfortunate way to this,
All pending commands are going to hang because the futures aren't resolved.
...

Well, the onError handler should be provided and a custom exception could be thrown. I saw that you already did that in your PR. I'll take a deeper look to it after.

**Comment by jonasfj** [comment]
> But note that the reconnection could not satisfy the client expectation when using the "pipelining" feature. And the reconnection should be disabled when using the "fire and forget" feature.

Given that redis can be used for many different things: a simple cache (instead of memcached), session store, work-queue, pub-sub message exchanges. I would suggest that this library doesn't necessarily have to implement a reconnection strategy, since there is many different opinions on how to do this.

But exposing a manner in which errors can be handled is necessary for others to implement reconnection logic, on top of this library.

**Comment by jcmellado** [comment]
I merged https://github.com/jcmellado/dartis/pull/12, but I can not get it working on my local machine.

> TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.

I got this error on the two new tests added to `client_test` and `connection_test`.

Travis is working fine.

**Comment by jonasfj** [comment]
Hmm, I tried it on a cloud instance and I also get some timeouts...

I'm not exactly sure if there is a better way to do this... Maybe we should be piping manually and then break the pipe, it could be that calling `destroy` while something is being piped is undefined behavior.

Maybe sockets just behave differently on windows, I'm rather unfamiliar with Windows.

But in general, I find that there aren't many good ways to simulate flaky connections.

**Comment by jcmellado** [comment]
I can't get this working. Any idea?
